# HW01
**Студент:** Чайка Никита Валентинович  
**Группа:** ИНБО-10-22

## 1. Импорт библиотеки NumPy с общепринятым сокращением

In [20]:
import numpy as np

## 2. Примеры создания массивов

In [21]:
# Из обычных списков
list_data = [0, 1, 2, 3, 4]
array_from_list = np.array(list_data)
print(f"Исходный список: {list_data}")
print(f"Numpy массив: {array_from_list}")
print(f"Тип массива: {type(array_from_list)}\n")

Исходный список: [0, 1, 2, 3, 4]
Numpy массив: [0 1 2 3 4]
Тип массива: <class 'numpy.ndarray'>



In [ ]:
# С использованием функций `zeros`, `ones`, `arange` или аналогичных.
zeros_array = np.zeros(3)
ones_array = np.ones(5)
arange_array = np.arange(0, 8, 2)  # Массив от 0 до 8 с шагом 2

print("Массив из нулей:")
print(zeros_array)
print(f"Shape: {zeros_array.shape}, Dtype: {zeros_array.dtype}\n")

print("Массив из единиц:")
print(ones_array)
print(f"Shape: {ones_array.shape}, Dtype: {ones_array.dtype}\n")

print("Массив с помощью arange:")
print(arange_array)
print(f"Shape: {arange_array.shape}, Dtype: {arange_array.dtype}\n")

Массив из нулей:
[0. 0. 0.]
Shape: (3,), Dtype: float64

Массив из единиц:
[1. 1. 1. 1. 1.]
Shape: (5,), Dtype: float64

Массив с помощью arange:
[0 2 4 6]
Shape: (4,), Dtype: int64



## 3. Демонстрация атрибутов

In [23]:
# Вывод формы (shape) и типа данных (dtype) для одного из массивов.
print(f"Массив: {array_from_list}")
print(f"- Форма (shape): {array_from_list.shape}")
print(f"- Тип данных (dtype): {array_from_list.dtype}\n")

Массив: [0 1 2 3 4]
- Форма (shape): (5,)
- Тип данных (dtype): int64



## 4. Примеры индексирования и срезов

In [24]:
print(f"Исходный массив: {array_from_list}")

# Получение отдельного элемента
element = array_from_list[2]
print(f"Элемент на позиции [2]: {element}")

# Извлечение подмассива с помощью среза
subarray = array_from_list[1:4]
print(f"Срез [1:4]: {subarray}\n")

Исходный массив: [0 1 2 3 4]
Элемент на позиции [2]: 2
Срез [1:4]: [1 2 3]



## 5. Примеры векторных операций и базовых статистик

In [25]:
array_a = np.array([0, 1, 2, 3, 4])
array_b = np.array([0, 10, 20, 30, 40])

print(f"Массив A: {array_a}")
print(f"Массив B: {array_b}")

# Поэлементное сложение
sum_result = array_a + array_b
print(f"\nПоэлементное сложение (A + B): {sum_result}")

# Поэлементное умножение
product_result = array_a * array_b
print(f"Поэлементное умножение (A * B): {product_result}")

Массив A: [0 1 2 3 4]
Массив B: [ 0 10 20 30 40]

Поэлементное сложение (A + B): [ 0 11 22 33 44]
Поэлементное умножение (A * B): [  0  10  40  90 160]


In [26]:
# Вычисление средней величины (`mean`) или другой простой статистики.
print(f"Среднее значение (mean): {np.mean(array_a):.2f}")

Среднее значение (mean): 2.00
